
			<?php $model="";?>
			<?php $product_id="";?>
			<?php $store_id="";?>
			<?php $store_id=Mage::app()->getStore()->getStoreId();?>
			<?php $model=Mage::getModel("laybuy/express");?>
			<?php $quote=Mage::getModel('checkout/cart')->getQuote();?>
			<?php $product_id = Mage::registry('current_product')->getId();?>
			<?php if($model->isAvailable($quote) && $model->checkForCategoriesAndProducts($product_id,$store_id)){// ?>
				<p class="paypal-logo">
					<?php if ($this->isOrPositionBefore()): ?>
						<span class="paypal-or"><?php echo $this->__('-OR-');?></span>
					<?php endif; ?>
				
							<a id="laybuy_express_link" style="cursor: pointer;float:left;"><img src="https://lay-buys.com/gateway/LAY-BUY.png" alt="<?php echo Mage::helper('laybuy')->__('Checkout with Laybuy Express');?>" title="<?php echo Mage::helper('laybuy')->__('Checkout with Laybuy Express');?>" /></a>
							<span id="payment-please-wait" class="please-wait" style="display:none;margin:5px;float:left;">
								<img class="v-middle" title="Loading next step..." alt="Loading next step..." src="<?php echo Mage::getBaseUrl("skin");?>frontend/default/default/images/opc-ajax-loader.gif"/>
							</span>
					<p style="clear:both;"></p>
					<?php if ($this->isOrPositionAfter()): ?>
					<span class="paypal-or"><?php echo $this->__('-OR-');?></span>
					<?php endif; ?>
				</p>
				
				<script type="text/javascript">
				laybuy(document).ready(function(){
							laybuy("a#laybuy_express_link").click(function(){
								laybuy("#payment-please-wait").css("display","block");
								var other_data = laybuy('#product_addtocart_form').serialize();
								var url=laybuy('#product_addtocart_form').attr('action');
								var url1='<?php echo Mage::getBaseurl();?>laybuy/express';
								laybuy.post( url, other_data,function(data){
												window.location = url1;		
									});
							});

					});
				
				</script>
			
		<?php }?>
