			<?php $model="";?>
			<?php $product_id="";?>
			<?php $store_id="";?>
			<?php $store_id=Mage::app()->getStore()->getStoreId();?>
			<?php $quote=Mage::getModel('checkout/cart')->getQuote();?>
			<?php $model=Mage::getModel("laybuy/express");?>
			<?php if($model->isAvailable($quote)){ // && $model->checkForCategoriesAndProducts($product_id,$store_id)?>
					<p class="paypal-logo">
					<?php if ($this->isOrPositionBefore()): ?>
					    <span class="paypal-or"><?php echo $this->__('-OR-');?></span>
					<?php endif; ?>
					   <a id="laybuy_express_link" style="cursor: pointer;" href="<?php echo Mage::getBaseurl();?>laybuy/express" ><img src="https://lay-buys.com/gateway/LAY-BUY.png" alt="<?php echo Mage::helper('laybuy')->__('Checkout with Laybuy Express');?>" title="<?php echo Mage::helper('laybuy')->__('Checkout with Laybuy Express');?>" /></a>
					<?php if ($this->isOrPositionAfter()): ?>
					    <span class="paypal-or"><?php echo $this->__('-OR-');?></span>
					<?php endif; ?>
					</p>
			<?php }?>
